# Generated by Django 3.2.7 on 2021-09-22 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="country",
            field=models.CharField(
                choices=[
                    ("kenya", "Kenya"),
                    ("tanzania", "Tanzania"),
                    ("uganda", "Uganda"),
                    ("rwanda", "Rwanda"),
                ],
                default="kenya",
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("management", "Management"),
                    ("sales", "Sales"),
                    ("customer", "Customer"),
                    ("undefined", "Undefined"),
                ],
                default="undefined",
                max_length=15,
            ),
        ),
    ]
