# Generated by Django 3.2.7 on 2021-09-22 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_remove_user_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="slug",
        ),
    ]
