# Generated by Django 3.2.7 on 2021-09-22 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='owner',
            new_name='created_by',
        ),
    ]
