# Generated by Django 3.2.7 on 2021-09-22 18:32

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_owner_products_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='country',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('kenya', 'Kenya'), ('tanzania', 'Tanzania'), ('uganda', 'Uganda'), ('rwanda', 'Rwanda')], default='kenya', max_length=15), size=None),
        ),
    ]
